/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RouteStop,
    RouteStopFromJSON,
    RouteStopFromJSONTyped,
    RouteStopToJSON,
} from './';

/**
 * 
 * @export
 * @interface CalculateRouteDTO
 */
export interface CalculateRouteDTO {
    /**
     * 
     * @type {Array<RouteStop>}
     * @memberof CalculateRouteDTO
     */
    routeStops: Array<RouteStop>;
}

export function CalculateRouteDTOFromJSON(json: any): CalculateRouteDTO {
    return CalculateRouteDTOFromJSONTyped(json, false);
}

export function CalculateRouteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalculateRouteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'routeStops': ((json['routeStops'] as Array<any>).map(RouteStopFromJSON)),
    };
}

export function CalculateRouteDTOToJSON(value?: CalculateRouteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'routeStops': ((value.routeStops as Array<any>).map(RouteStopToJSON)),
    };
}


