/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteRouteStopDTO
 */
export interface CompleteRouteStopDTO {
    /**
     * 
     * @type {number}
     * @memberof CompleteRouteStopDTO
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CompleteRouteStopDTO
     */
    completionDatetime: Date;
}

export function CompleteRouteStopDTOFromJSON(json: any): CompleteRouteStopDTO {
    return CompleteRouteStopDTOFromJSONTyped(json, false);
}

export function CompleteRouteStopDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteRouteStopDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'completionDatetime': (new Date(json['completionDatetime'])),
    };
}

export function CompleteRouteStopDTOToJSON(value?: CompleteRouteStopDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'completionDatetime': (value.completionDatetime.toISOString()),
    };
}


