/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserRoles,
    UserRolesFromJSON,
    UserRolesFromJSONTyped,
    UserRolesToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateUserDTO
 */
export interface CreateUserDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    email?: string;
    /**
     * 
     * @type {UserRoles}
     * @memberof CreateUserDTO
     */
    roles?: UserRoles;
}

export function CreateUserDTOFromJSON(json: any): CreateUserDTO {
    return CreateUserDTOFromJSONTyped(json, false);
}

export function CreateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'roles': !exists(json, 'roles') ? undefined : UserRolesFromJSON(json['roles']),
    };
}

export function CreateUserDTOToJSON(value?: CreateUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'displayName': value.displayName,
        'email': value.email,
        'roles': UserRolesToJSON(value.roles),
    };
}


