/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Destination
 */
export interface Destination {
    /**
     * 
     * @type {number}
     * @memberof Destination
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Destination
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Destination
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Destination
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Destination
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Destination
     */
    references?: string;
    /**
     * 
     * @type {number}
     * @memberof Destination
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof Destination
     */
    latitude: number;
    /**
     * 
     * @type {boolean}
     * @memberof Destination
     */
    isOwnCompany: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Destination
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Destination
     */
    updatedAt: Date;
}

export function DestinationFromJSON(json: any): Destination {
    return DestinationFromJSONTyped(json, false);
}

export function DestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Destination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'references': !exists(json, 'references') ? undefined : json['references'],
        'longitude': json['longitude'],
        'latitude': json['latitude'],
        'isOwnCompany': json['isOwnCompany'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function DestinationToJSON(value?: Destination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'code': value.code,
        'email': value.email,
        'phone': value.phone,
        'references': value.references,
        'longitude': value.longitude,
        'latitude': value.latitude,
        'isOwnCompany': value.isOwnCompany,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}


