/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Place,
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchPlacesResponse
 */
export interface SearchPlacesResponse {
    /**
     * 
     * @type {Array<Place>}
     * @memberof SearchPlacesResponse
     */
    places: Array<Place>;
}

export function SearchPlacesResponseFromJSON(json: any): SearchPlacesResponse {
    return SearchPlacesResponseFromJSONTyped(json, false);
}

export function SearchPlacesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlacesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'places': ((json['places'] as Array<any>).map(PlaceFromJSON)),
    };
}

export function SearchPlacesResponseToJSON(value?: SearchPlacesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'places': ((value.places as Array<any>).map(PlaceToJSON)),
    };
}


