/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInResponseDTO
 */
export interface SignInResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof SignInResponseDTO
     */
    accessToken: string;
}

export function SignInResponseDTOFromJSON(json: any): SignInResponseDTO {
    return SignInResponseDTOFromJSONTyped(json, false);
}

export function SignInResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function SignInResponseDTOToJSON(value?: SignInResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
    };
}


