/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartRouteStopDTO
 */
export interface StartRouteStopDTO {
    /**
     * 
     * @type {number}
     * @memberof StartRouteStopDTO
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof StartRouteStopDTO
     */
    startDatetime: Date;
}

export function StartRouteStopDTOFromJSON(json: any): StartRouteStopDTO {
    return StartRouteStopDTOFromJSONTyped(json, false);
}

export function StartRouteStopDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartRouteStopDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDatetime': (new Date(json['startDatetime'])),
    };
}

export function StartRouteStopDTOToJSON(value?: StartRouteStopDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'startDatetime': (value.startDatetime.toISOString()),
    };
}


