/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDestinationDTO
 */
export interface UpdateDestinationDTO {
    /**
     * 
     * @type {number}
     * @memberof UpdateDestinationDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateDestinationDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDestinationDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDestinationDTO
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDestinationDTO
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDestinationDTO
     */
    references?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateDestinationDTO
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDestinationDTO
     */
    latitude?: number;
}

export function UpdateDestinationDTOFromJSON(json: any): UpdateDestinationDTO {
    return UpdateDestinationDTOFromJSONTyped(json, false);
}

export function UpdateDestinationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDestinationDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'references': !exists(json, 'references') ? undefined : json['references'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
    };
}

export function UpdateDestinationDTOToJSON(value?: UpdateDestinationDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'phone': value.phone,
        'code': value.code,
        'references': value.references,
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}


