/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RouteGeometry,
    RouteGeometryFromJSON,
    RouteGeometryFromJSONTyped,
    RouteGeometryToJSON,
    RouteStop,
    RouteStopFromJSON,
    RouteStopFromJSONTyped,
    RouteStopToJSON,
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateRouteDTO
 */
export interface UpdateRouteDTO {
    /**
     * 
     * @type {number}
     * @memberof UpdateRouteDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateRouteDTO
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateRouteDTO
     */
    distance: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRouteDTO
     */
    duration: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateRouteDTO
     */
    durationWithLoadTime: number;
    /**
     * 
     * @type {RouteGeometry}
     * @memberof UpdateRouteDTO
     */
    geometry: RouteGeometry;
    /**
     * 
     * @type {Date}
     * @memberof UpdateRouteDTO
     */
    started: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateRouteDTO
     */
    completed: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateRouteDTO
     */
    completedDuration: number;
    /**
     * 
     * @type {Array<RouteStop>}
     * @memberof UpdateRouteDTO
     */
    stops: Array<RouteStop>;
    /**
     * 
     * @type {User}
     * @memberof UpdateRouteDTO
     */
    driver: User;
}

export function UpdateRouteDTOFromJSON(json: any): UpdateRouteDTO {
    return UpdateRouteDTOFromJSONTyped(json, false);
}

export function UpdateRouteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRouteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'distance': json['distance'],
        'duration': json['duration'],
        'durationWithLoadTime': json['durationWithLoadTime'],
        'geometry': RouteGeometryFromJSON(json['geometry']),
        'started': (new Date(json['started'])),
        'completed': (new Date(json['completed'])),
        'completedDuration': json['completedDuration'],
        'stops': ((json['stops'] as Array<any>).map(RouteStopFromJSON)),
        'driver': UserFromJSON(json['driver']),
    };
}

export function UpdateRouteDTOToJSON(value?: UpdateRouteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'distance': value.distance,
        'duration': value.duration,
        'durationWithLoadTime': value.durationWithLoadTime,
        'geometry': RouteGeometryToJSON(value.geometry),
        'started': (value.started.toISOString()),
        'completed': (value.completed.toISOString()),
        'completedDuration': value.completedDuration,
        'stops': ((value.stops as Array<any>).map(RouteStopToJSON)),
        'driver': UserToJSON(value.driver),
    };
}


