/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAnalyticsDTOUser
 */
export interface UserAnalyticsDTOUser {
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTOUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserAnalyticsDTOUser
     */
    displayName?: string;
}

export function UserAnalyticsDTOUserFromJSON(json: any): UserAnalyticsDTOUser {
    return UserAnalyticsDTOUserFromJSONTyped(json, false);
}

export function UserAnalyticsDTOUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnalyticsDTOUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function UserAnalyticsDTOUserToJSON(value?: UserAnalyticsDTOUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'displayName': value.displayName,
    };
}


