/* tslint:disable */
/* eslint-disable */
/**
 * Distrologiq
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerformanceHistoryChartItem,
    PerformanceHistoryChartItemFromJSON,
    PerformanceHistoryChartItemFromJSONTyped,
    PerformanceHistoryChartItemToJSON,
    UserAnalyticsDTOUser,
    UserAnalyticsDTOUserFromJSON,
    UserAnalyticsDTOUserFromJSONTyped,
    UserAnalyticsDTOUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserAnalyticsDTO
 */
export interface UserAnalyticsDTO {
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    assignedRoutesCount: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    completedRoutesCount: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    pendingRoutesCount: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    averagePerformance: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    averageVisits: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    averageRouteDuration: number;
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsDTO
     */
    accumulatedDistance: number;
    /**
     * 
     * @type {Array<PerformanceHistoryChartItem>}
     * @memberof UserAnalyticsDTO
     */
    performanceHistoryChart: Array<PerformanceHistoryChartItem>;
    /**
     * 
     * @type {UserAnalyticsDTOUser}
     * @memberof UserAnalyticsDTO
     */
    user: UserAnalyticsDTOUser;
}

export function UserAnalyticsDTOFromJSON(json: any): UserAnalyticsDTO {
    return UserAnalyticsDTOFromJSONTyped(json, false);
}

export function UserAnalyticsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnalyticsDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignedRoutesCount': json['assignedRoutesCount'],
        'completedRoutesCount': json['completedRoutesCount'],
        'pendingRoutesCount': json['pendingRoutesCount'],
        'averagePerformance': json['averagePerformance'],
        'averageVisits': json['averageVisits'],
        'averageRouteDuration': json['averageRouteDuration'],
        'accumulatedDistance': json['accumulatedDistance'],
        'performanceHistoryChart': ((json['performanceHistoryChart'] as Array<any>).map(PerformanceHistoryChartItemFromJSON)),
        'user': UserAnalyticsDTOUserFromJSON(json['user']),
    };
}

export function UserAnalyticsDTOToJSON(value?: UserAnalyticsDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assignedRoutesCount': value.assignedRoutesCount,
        'completedRoutesCount': value.completedRoutesCount,
        'pendingRoutesCount': value.pendingRoutesCount,
        'averagePerformance': value.averagePerformance,
        'averageVisits': value.averageVisits,
        'averageRouteDuration': value.averageRouteDuration,
        'accumulatedDistance': value.accumulatedDistance,
        'performanceHistoryChart': ((value.performanceHistoryChart as Array<any>).map(PerformanceHistoryChartItemToJSON)),
        'user': UserAnalyticsDTOUserToJSON(value.user),
    };
}


